[package]
name = "btc_rpc_proxy"
version = "0.1.0"
authors = ["Martin Habovštiak <martin.habovstiak@gmail.com>"]
build = "build.rs"

[dependencies]
hyper = "0.11.2"
futures = "0.1"
tokio-core = "0.1"
serde = "1"
serde_derive = "1"
serde_json = "1"
toml = "0.4"
slog = "2.2.3"
slog-term = "2.4"
slog-async = "2.3"
configure_me = "0.3.2"

[build_dependencies]
configure_me_codegen = "0.3.4"
