name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use old rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.41.1
        override: true

    - name: Build
      run: cargo build --features=old_rust --verbose
    - name: Run tests
      run: cargo test --features=old_rust --verbose
